# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    description: "this is a way to print the workflow id "
    steps:
        - run: echo $CIRCLE_WORKFLOW_ID
# Orchestrate or schedule a set of jobs
jobs:
  Print_My_Name:
    docker:
      - image: circleci/node:13.8.0    
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $MY_FST_EV is my name 

  invoke_command:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id

  job_fail:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run: 
          name: an error
          command: echo "Job error"
          when: on_fail
  smoke_test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: smoke tesing  google
          command: |
            if curl -s --head "https://google22.com" 
              then
                return 0
              else
                return 1
              fi          

  
workflows:      
  # Name the workflow "welcome"
  share:
    jobs:
      - Print_My_Name
      - invoke_command
      - job_fail
      - smoke_test